trigger:
  batch: true
  branches:
    include:
    - main

pr: 
  - main
name: Jmeter regression pipeline $(date:yyyyMMdd)$(rev:.r)

pool: Default

steps:
- script: |
    wget -c รง
    tar -xf apache-jmeter-5.6.3.tgz
  displayName: 'Install the dependency packages'
  
- script: |
        apache-jmeter-5.6.3/bin/./jmeter -Jjmeter.reportgenerator.overall_granularity=1000 -n -t api/test.jmx -l results/results.jtl -j results/output.log -e -o report
  displayName: 'Run JMeter'

- task: PublishPipelineArtifact@1
  displayName: 'Publish JMeter HTML Report'
  inputs:
    targetPath: report
    artifact: jmeter-report