name: API Test Execution

on:
  workflow_dispatch:

  push:
    branches: [main]
  
  pull_request:
    
jobs:
  api_test_standalone:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Create reports directory
        run: mkdir reports

      - name: Set up Java
        uses: actions/setup-java@v1
        with:
          java-version: 11  # Adjust to your Java version

      - name: Download and Install JMeter
        run: |
          wget -q https://archive.apache.org/dist/jmeter/binaries/apache-jmeter-5.6.3.tgz
          tar -xf apache-jmeter-5.6.3.tgz
          rm apache-jmeter-5.6.3.tgz

      - name: Run JMeter test
        run: |
          ./apache-jmeter-5.6.3/bin/jmeter -J-Xms2g -J-Xmx16g -n -t api/test.jmx -l result.jtl -e -o ./reports/html/

      - name: Upload Results
        uses: actions/upload-artifact@v3
        if: ${{ !cancelled() }}
        with:
          name: jmeter-results
          path: result.jtl
          if-no-files-found: error  

      - name: Upload HTML Reports
        uses: actions/upload-artifact@v3
        if: ${{ !cancelled() }}
        with:
          name: jmeter-html-reports
          path: reports
          if-no-files-found: error
